#
# Copyright (C) 2008-2011 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

endef

define Package/batmand/
/etc/batmand
endef

$(eval $(call BuildPackage,batmand))
