# SPDX-License-Identifier: GPL-2.0-only
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
# Copyright (C) 2022 - 2024 BlueWave Projects and Services  <licence@blue-wave.net>
#

include $(TOPDIR)/rules.mk


define Build/Compile
endef

$(eval $(call BuildPackage,mesh11sd))
