#!/bin/sh /etc/rc.common
START=0
USE_PROCD=0

BIN=/usr/sbin/bmx7
CONF=/etc/config/

start_service() {
	cd /rm/ || return
	while pgrep -f mac80211.sh ; do sleep 1; done

	procd_set_param respawn
	procd_close_instance

}
