#
# Copyright (C) 2014 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.

include $(TOPDIR)/rules.mk

exit 0
endef

$(eval $(call BuildPackage,minimalist-pcproxy))
