#!/bin/sh /etc/rc.common
START=0
USE_PROCD=0

batmand_start() {

	local disable_aggregation

	[ "$config" = "general" ] || return 1

	config_get interface "$config" interface
	if [ "$interface" = "" ]; then
		echo $1 Error, you must specify at least a network interface
		return 1
	fi

	config_get disable_aggregation "$config" disable_aggregation

	batman_args=""

	for hna in $hnas; do
		batman_args=${batman_args}'-a '$hna' '
	done

	if [ $gateway_class ]; then

	procd_close_instance
}

start_service() {
	config_load "batmand"
	config_foreach batmand_start batmand
}

service_triggers() {
	procd_add_reload_trigger "batmand"
}
